name: Deployment Pipeline

on:
  push:
    branches: [main]  
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  Cancel:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with: 
          token: ${{ github.token }}

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
        run: yarn install
      - name: Testing
        run: yarn test

  Deploy:
    if: ${{ github.event_name == 'push' }}
    needs: ['Test']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
        run: yarn install
      - name: Testing
        run: yarn test
      - name: Deploy
        run: echo Deploy